import React from 'react';
import { Repeat, ArrowRight, Clock, Plus, Camera } from 'lucide-react';
import { Expense, ExpenseCategory, RecurringExpense, UserSettings, CategoryItem } from '../types';
import { DailyStats } from './DailyStats';
import { AIInsightsSection } from './AIInsightsSection';
import { CategoryBreakdown } from './CategoryBreakdown';
import { ExpenseCard } from './ExpenseCard';
import { PWAInstallButton } from './PWAInstallButton';
import { QuickAddExpenseCard } from './QuickAddExpenseCard';

interface HomeViewProps {
  expenses: Expense[];
  settings: UserSettings;
  categories: CategoryItem[];
  recurringExpenses: RecurringExpense[];
  autoGeneratedAlert: { count: number; items: string[] } | null;
  onClearAutoGeneratedAlert: () => void;
  onOpenRecurring: () => void;
  onOpenBudgetWallets: () => void;
  onNavigateToTransactions: (category?: ExpenseCategory) => void;
  onNavigateToBudgets: () => void;
  onReviewTransaction: (expense: Expense) => void;
  onSelectExpense: (expense: Expense) => void;
  onEditExpense: (expense: Expense) => void;
  onDeleteExpense: (id: string) => void;
  onOpenAddExpense: () => void;
  onOpenScanner: () => void;
  onSaveExpense: (expense: Omit<Expense, 'id' | 'createdAt'>) => void;
  onOpenQuickAddChat?: () => void;
  isDark?: boolean;
}

export const HomeView: React.FC<HomeViewProps> = ({
  expenses,
  settings,
  categories,
  recurringExpenses,
  autoGeneratedAlert,
  onClearAutoGeneratedAlert,
  onOpenRecurring,
  onOpenBudgetWallets,
  onNavigateToTransactions,
  onNavigateToBudgets,
  onReviewTransaction,
  onSelectExpense,
  onEditExpense,
  onDeleteExpense,
  onOpenAddExpense,
  onOpenScanner,
  onSaveExpense,
  onOpenQuickAddChat,
  isDark = true,
}) => {
  // Recent 4 transactions
  const recentTransactions = [...expenses]
    .sort((a, b) => {
      if (b.date !== a.date) return b.date.localeCompare(a.date);
      return (b.time || '').localeCompare(a.time || '');
    })
    .slice(0, 4);

  return (
    <div className="space-y-4">
      {/* Auto-Generated Recurring Expenses Banner Alert */}
      {autoGeneratedAlert && (
        <div className="rounded-2xl border border-purple-500/40 bg-purple-950/70 p-3.5 flex items-center justify-between text-xs text-purple-200 shadow-xl backdrop-blur-md">
          <div className="flex items-center gap-2.5 min-w-0">
            <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-xl bg-purple-500/20 text-purple-300 border border-purple-500/30">
              <Repeat className="h-4 w-4 animate-spin" style={{ animationDuration: '6s' }} />
            </div>
            <div className="min-w-0 flex-1">
              <p className="font-semibold text-white truncate">
                {autoGeneratedAlert.count} recurring {autoGeneratedAlert.count > 1 ? 'entries' : 'entry'} auto-logged!
              </p>
              <p className="text-[11px] text-purple-300/80 truncate">
                {autoGeneratedAlert.items.join(', ')}
              </p>
            </div>
          </div>
          <div className="flex items-center gap-1.5 shrink-0 ml-2">
            <button
              type="button"
              onClick={() => {
                onClearAutoGeneratedAlert();
                onOpenRecurring();
              }}
              className="rounded-lg bg-purple-600 hover:bg-purple-500 px-2.5 py-1 text-[11px] font-semibold text-white shadow transition active:scale-95"
            >
              View
            </button>
            <button
              type="button"
              onClick={onClearAutoGeneratedAlert}
              className="rounded-lg p-1 text-slate-400 hover:text-white transition"
              title="Dismiss notification"
            >
              ✕
            </button>
          </div>
        </div>
      )}

      {/* In-app Install banner if not installed */}
      <PWAInstallButton variant="banner" />

      {/* Daily & Monthly Financial Stats (Income, Expense, Net & Recurring Forecast) */}
      <DailyStats
        expenses={expenses}
        currencySymbol={settings.currencySymbol}
        monthlyBudget={settings.monthlyBudget}
        recurringExpenses={recurringExpenses}
        onOpenBudgetWallets={onNavigateToBudgets}
        isDark={isDark}
      />

      {/* Quick Add Expense (Natural Language & Chat) */}
      <QuickAddExpenseCard
        onSaveExpense={onSaveExpense}
        onOpenFullEdit={(draft) => {
          onReviewTransaction(draft as Expense);
        }}
        onOpenFullChatModal={onOpenQuickAddChat}
        defaultCurrency={settings.currency}
        customCategories={categories}
        isDark={isDark}
      />

      {/* Automatic Deterministic Spending Alerts Section */}
      <AIInsightsSection
        expenses={expenses}
        settings={settings}
        isDark={isDark}
        onOpenBudgetWallets={onNavigateToBudgets}
        onViewSpending={(category) => {
          onNavigateToTransactions(category ? (category as ExpenseCategory) : undefined);
        }}
        onReviewTransaction={onReviewTransaction}
        onOpenAddExpense={onOpenAddExpense}
      />

      {/* Category Breakdown Meter */}
      <CategoryBreakdown
        expenses={expenses}
        currencySymbol={settings.currencySymbol}
        selectedCategory="All"
        onSelectCategory={(cat) => {
          if (cat !== 'All') {
            onNavigateToTransactions(cat);
          }
        }}
        customCategories={categories}
        isDark={isDark}
      />

      {/* Recent Activity Section */}
      <div className="space-y-2.5 pt-1">
        <div className="flex items-center justify-between px-1">
          <div className="flex items-center gap-1.5">
            <Clock className="h-3.5 w-3.5 text-indigo-400" />
            <h3 className={`text-xs font-bold uppercase tracking-wider ${isDark ? 'text-slate-300' : 'text-slate-700'}`}>
              Recent Activity
            </h3>
          </div>
          {expenses.length > 0 && (
            <button
              type="button"
              onClick={() => onNavigateToTransactions()}
              className="flex items-center gap-1 text-xs font-semibold text-indigo-400 hover:text-indigo-300 transition"
            >
              <span>View all ({expenses.length})</span>
              <ArrowRight className="h-3.5 w-3.5" />
            </button>
          )}
        </div>

        {recentTransactions.length === 0 ? (
          <div
            className={`rounded-3xl border border-dashed p-6 text-center space-y-3 ${
              isDark ? 'border-white/10 bg-white/5' : 'border-slate-300 bg-white'
            }`}
          >
            <p className="text-xs font-semibold text-slate-300">No transactions recorded yet</p>
            <p className="text-[11px] text-slate-400 max-w-xs mx-auto">
              Scan your paper receipts or add expenses manually to monitor your spending in real time.
            </p>
            <div className="flex justify-center gap-2 pt-1">
              <button
                type="button"
                onClick={onOpenScanner}
                className="min-h-[44px] flex items-center gap-1.5 rounded-xl bg-gradient-to-r from-indigo-600 to-purple-600 px-3.5 py-2 text-xs font-semibold text-white shadow-md"
              >
                <Camera className="h-3.5 w-3.5" />
                <span>Scan Receipt</span>
              </button>
              <button
                type="button"
                onClick={onOpenAddExpense}
                className={`min-h-[44px] flex items-center gap-1.5 rounded-xl border px-3.5 py-2 text-xs font-semibold ${
                  isDark ? 'border-white/10 bg-white/5 text-slate-200' : 'border-slate-200 bg-slate-100 text-slate-700'
                }`}
              >
                <Plus className="h-3.5 w-3.5" />
                <span>Add Expense</span>
              </button>
            </div>
          </div>
        ) : (
          <div className="space-y-2">
            {recentTransactions.map((expense) => (
              <ExpenseCard
                key={expense.id}
                expense={expense}
                currencySymbol={settings.currencySymbol}
                customCategories={categories}
                isDark={isDark}
                onClick={() => onSelectExpense(expense)}
                onEdit={() => onEditExpense(expense)}
                onDelete={() => onDeleteExpense(expense.id)}
              />
            ))}
          </div>
        )}
      </div>
    </div>
  );
};
