import React, { useState, useMemo, useEffect } from 'react';
import {
  Moon,
  Sun,
} from 'lucide-react';
import { useExpenses } from './hooks/useExpenses';
import { AndroidFrame } from './components/AndroidFrame';
import { BottomNavigation, NavDestination } from './components/BottomNavigation';
import { HomeView } from './components/HomeView';
import { TransactionsView, DateFilterType, TxTypeFilter } from './components/TransactionsView';
import { BudgetsView } from './components/BudgetsView';
import { SettingsView } from './components/SettingsView';
import { ReceiptScannerModal } from './components/ReceiptScannerModal';
import { QuickAddExpenseModal } from './components/QuickAddExpenseModal';
import { AddExpenseModal } from './components/AddExpenseModal';
import { ExpenseDetailModal } from './components/ExpenseDetailModal';
import { CategoryManagerModal } from './components/CategoryManagerModal';
import { RecurringExpensesModal } from './components/RecurringExpensesModal';
import { InteractiveWalkthrough } from './components/InteractiveWalkthrough';
import { BudgetWalletsModal } from './components/BudgetWalletsModal';
import { ExcelImportModal } from './components/ExcelImportModal';
import { PWAInstallButton } from './components/PWAInstallButton';
import { PWAUpdateBanner } from './components/PWAUpdateBanner';
import { usePWAUpdate } from './hooks/usePWAUpdate';
import { Expense, ExpenseCategory, TransactionType } from './types';
import { calculateSpendingAlerts } from './utils/spendingAlerts';
import { exportExpensesToExcel } from './utils/spreadsheetParser';

export default function App() {
  const {
    needRefresh,
    isChecking: isCheckingUpdate,
    checkStatus: updateCheckStatus,
    lastChecked,
    checkForUpdate,
    updateApp,
    forceClearCacheAndReload,
    dismissRefreshPrompt,
  } = usePWAUpdate();

  const {
    expenses,
    settings,
    categories,
    recurringExpenses,
    autoGeneratedAlert,
    clearAutoGeneratedAlert,
    addExpense,
    addMultipleExpenses,
    updateExpense,
    deleteExpense,
    clearAllExpenses,
    updateSettings,
    updateCategoryBudgetConfig,
    toggleTheme,
    addCategory,
    updateCategory,
    deleteCategory,
    addRecurringExpense,
    updateRecurringExpense,
    deleteRecurringExpense,
    toggleRecurringActive,
    processDueRecurring,
    exportCSV,
    exportJSON,
    importJSON,
  } = useExpenses();

  const isDark = settings.theme !== 'light';

  // Navigation State
  const [currentTab, setCurrentTab] = useState<NavDestination>('home');

  // Modals state
  const [isScannerOpen, setIsScannerOpen] = useState(false);
  const [isQuickAddModalOpen, setIsQuickAddModalOpen] = useState(false);
  const [isAddOpen, setIsAddOpen] = useState(false);
  const [isExcelImportOpen, setIsExcelImportOpen] = useState(false);
  const [addModalInitialType, setAddModalInitialType] = useState<TransactionType>('expense');
  const [isCategoryManagerOpen, setIsCategoryManagerOpen] = useState(false);
  const [isRecurringOpen, setIsRecurringOpen] = useState(false);
  const [isBudgetWalletsOpen, setIsBudgetWalletsOpen] = useState(false);
  const [isWalkthroughOpen, setIsWalkthroughOpen] = useState(false);
  const [selectedExpense, setSelectedExpense] = useState<Expense | null>(null);
  const [editingExpense, setEditingExpense] = useState<Expense | null>(null);

  // Auto show walkthrough for new users on their very first visit
  useEffect(() => {
    const guideSeen = localStorage.getItem('receipt_tracker_guide_seen');
    if (!guideSeen) {
      setIsWalkthroughOpen(true);
    }
  }, []);

  // Filter state for Transactions tab
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedCategory, setSelectedCategory] = useState<ExpenseCategory | 'All'>('All');
  const [dateFilter, setDateFilter] = useState<DateFilterType>('all');
  const [txTypeFilter, setTxTypeFilter] = useState<TxTypeFilter>('all');

  // Count due recurring items
  const dueRecurringCount = useMemo(() => {
    const today = new Date().toISOString().slice(0, 10);
    return recurringExpenses.filter((r) => r.isActive && r.nextDueDate <= today).length;
  }, [recurringExpenses]);

  // Count active spending alerts
  const spendingAlerts = useMemo(() => {
    return calculateSpendingAlerts(expenses, settings);
  }, [expenses, settings]);

  // Handler to open Add Modal with a specific type
  const handleOpenAdd = (type: TransactionType) => {
    setEditingExpense(null);
    setAddModalInitialType(type);
    setIsAddOpen(true);
  };

  // Handler to open Edit Modal
  const handleOpenEdit = (expense: Expense) => {
    setEditingExpense(expense);
    setAddModalInitialType(expense.type || 'expense');
    setIsAddOpen(true);
  };

  // Switch to Transactions tab with pre-applied filter
  const handleNavigateToTransactions = (category?: ExpenseCategory) => {
    if (category) {
      setSelectedCategory(category);
      setTxTypeFilter('expense');
      setDateFilter('month');
    }
    setCurrentTab('transactions');
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  // Switch to Budgets tab
  const handleNavigateToBudgets = () => {
    setCurrentTab('budgets');
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  return (
    <AndroidFrame isDark={isDark}>
      <div className="flex flex-col min-h-full pb-32 relative">
        {/* PWA Update Banner */}
        <PWAUpdateBanner
          needRefresh={needRefresh}
          onUpdate={updateApp}
          onDismiss={dismissRefreshPrompt}
          isDark={isDark}
        />

        {/* Simplified Header */}
        <header
          className={`sticky top-0 z-20 border-b px-4 py-3 flex items-center justify-between transition-colors backdrop-blur-2xl ${
            isDark ? 'border-white/10 bg-[#060b18]/85' : 'border-slate-200 bg-white/95'
          }`}
        >
          <div className="flex items-center gap-2.5">
            <div className="relative flex h-10 w-10 shrink-0 items-center justify-center overflow-hidden rounded-2xl border border-white/20 shadow-lg bg-slate-900">
              <img
                src="/app-icon.jpg"
                alt="Daily Expense Tracker Icon"
                className="h-full w-full object-cover"
                referrerPolicy="no-referrer"
              />
            </div>
            <div>
              <div className="flex items-center gap-1.5">
                <h1
                  className={`text-sm font-bold tracking-tight ${
                    isDark ? 'text-white' : 'text-slate-900'
                  }`}
                >
                  Daily Expense
                </h1>
                {/* Default Currency Badge */}
                <span className="rounded-full bg-indigo-500/20 px-2 py-0.5 text-[10px] font-semibold text-indigo-400 border border-indigo-500/30">
                  {settings.currency}
                </span>
              </div>
              <p className={`text-[10px] ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>
                Expenses & Income Tracker
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            {/* PWA Install Button (if browser supports install) */}
            <PWAInstallButton variant="compact" />

            {/* Dark/Light Mode Switch */}
            <button
              type="button"
              id="header-theme-toggle"
              onClick={toggleTheme}
              className={`min-h-[44px] min-w-[44px] flex items-center justify-center rounded-2xl border transition active:scale-95 ${
                isDark
                  ? 'border-white/10 bg-white/5 text-amber-300 hover:bg-white/10'
                  : 'border-slate-200 bg-slate-100 text-slate-700 hover:bg-slate-200'
              }`}
              title={isDark ? 'Switch to Light Mode' : 'Switch to Dark Mode'}
              aria-label={isDark ? 'Switch to Light Mode' : 'Switch to Dark Mode'}
            >
              {isDark ? <Sun className="h-4 w-4" /> : <Moon className="h-4 w-4" />}
            </button>
          </div>
        </header>

        {/* Content Body */}
        <main className="flex-1 p-4">
          {currentTab === 'home' && (
            <HomeView
              expenses={expenses}
              settings={settings}
              categories={categories}
              recurringExpenses={recurringExpenses}
              autoGeneratedAlert={autoGeneratedAlert}
              onClearAutoGeneratedAlert={clearAutoGeneratedAlert}
              onOpenRecurring={() => setIsRecurringOpen(true)}
              onOpenBudgetWallets={() => setIsBudgetWalletsOpen(true)}
              onNavigateToTransactions={handleNavigateToTransactions}
              onNavigateToBudgets={handleNavigateToBudgets}
              onReviewTransaction={handleOpenEdit}
              onSelectExpense={setSelectedExpense}
              onEditExpense={handleOpenEdit}
              onDeleteExpense={deleteExpense}
              onOpenAddExpense={() => handleOpenAdd('expense')}
              onOpenScanner={() => setIsScannerOpen(true)}
              onSaveExpense={addExpense}
              onOpenQuickAddChat={() => setIsQuickAddModalOpen(true)}
              isDark={isDark}
            />
          )}

          {currentTab === 'transactions' && (
            <TransactionsView
              expenses={expenses}
              currencySymbol={settings.currencySymbol}
              categories={categories}
              searchQuery={searchQuery}
              onSearchChange={setSearchQuery}
              selectedCategory={selectedCategory}
              onCategoryChange={setSelectedCategory}
              dateFilter={dateFilter}
              onDateFilterChange={setDateFilter}
              txTypeFilter={txTypeFilter}
              onTxTypeFilterChange={setTxTypeFilter}
              onSelectExpense={setSelectedExpense}
              onEditExpense={handleOpenEdit}
              onDeleteExpense={deleteExpense}
              onOpenScanner={() => setIsScannerOpen(true)}
              onOpenAddExpense={() => handleOpenAdd('expense')}
              onOpenRecurring={() => setIsRecurringOpen(true)}
              onOpenExcelImport={() => setIsExcelImportOpen(true)}
              recurringExpensesCount={recurringExpenses.length}
              dueRecurringCount={dueRecurringCount}
              isDark={isDark}
            />
          )}

          {currentTab === 'budgets' && (
            <BudgetsView
              expenses={expenses}
              settings={settings}
              categories={categories}
              onUpdateSettings={updateSettings}
              onUpdateCategoryBudgetConfig={updateCategoryBudgetConfig}
              onOpenAddSavingsTransfer={() => {
                setEditingExpense({
                  id: '',
                  merchant: 'Savings Contribution',
                  amount: 100,
                  currency: settings.currency,
                  date: new Date().toISOString().slice(0, 10),
                  category: 'Savings',
                  paymentMethod: 'Bank Transfer',
                  createdAt: Date.now(),
                  type: 'expense',
                  tags: ['savings'],
                });
                setAddModalInitialType('expense');
                setIsAddOpen(true);
              }}
              isDark={isDark}
            />
          )}

          {currentTab === 'settings' && (
            <SettingsView
              settings={settings}
              onUpdateSettings={updateSettings}
              onToggleTheme={toggleTheme}
              onOpenCategoryManager={() => setIsCategoryManagerOpen(true)}
              onOpenWalkthrough={() => setIsWalkthroughOpen(true)}
              onExportCSV={exportCSV}
              onExportExcel={() => exportExpensesToExcel(expenses, settings.currencySymbol)}
              onOpenExcelImport={() => setIsExcelImportOpen(true)}
              onExportJSON={exportJSON}
              onImportJSON={importJSON}
              onClearAll={clearAllExpenses}
              expensesCount={expenses.length}
              isDark={isDark}
              onCheckForUpdate={checkForUpdate}
              isCheckingUpdate={isCheckingUpdate}
              updateCheckStatus={updateCheckStatus}
              onForceClearCache={forceClearCacheAndReload}
              lastChecked={lastChecked}
              needRefresh={needRefresh}
            />
          )}
        </main>

        {/* Unified 4-Destination Bottom Navigation + Combined "+ Add" Menu */}
        <BottomNavigation
          currentTab={currentTab}
          onSelectTab={(tab) => {
            setCurrentTab(tab);
            window.scrollTo({ top: 0, behavior: 'smooth' });
          }}
          onOpenScanner={() => setIsScannerOpen(true)}
          onOpenAddExpense={() => handleOpenAdd('expense')}
          onOpenAddIncome={() => handleOpenAdd('income')}
          onOpenQuickAdd={() => setIsQuickAddModalOpen(true)}
          dueRecurringCount={dueRecurringCount}
          alertsCount={spendingAlerts.length}
          isDark={isDark}
        />

        {/* Modals */}
        <QuickAddExpenseModal
          isOpen={isQuickAddModalOpen}
          onClose={() => setIsQuickAddModalOpen(false)}
          onSaveExpense={addExpense}
          onOpenFullEdit={handleOpenEdit}
          defaultCurrency={settings.currency}
          customCategories={categories}
          isDark={isDark}
        />

        <ReceiptScannerModal
          isOpen={isScannerOpen}
          onClose={() => setIsScannerOpen(false)}
          onSaveExpense={addExpense}
          onSaveMultipleExpenses={addMultipleExpenses}
          defaultCurrency={settings.currency}
          onOpenManual={() => {
            setIsScannerOpen(false);
            handleOpenAdd('expense');
          }}
        />

        <AddExpenseModal
          isOpen={isAddOpen}
          onClose={() => {
            setIsAddOpen(false);
            setEditingExpense(null);
          }}
          onSaveExpense={addExpense}
          onUpdateExpense={updateExpense}
          onAddRecurring={addRecurringExpense}
          defaultCurrency={settings.currency}
          categories={categories}
          onOpenCategoryManager={() => {
            setIsAddOpen(false);
            setIsCategoryManagerOpen(true);
          }}
          initialExpense={editingExpense}
          initialType={addModalInitialType}
          isDark={isDark}
        />

        <ExpenseDetailModal
          expense={selectedExpense}
          onClose={() => setSelectedExpense(null)}
          onUpdate={updateExpense}
          onDelete={deleteExpense}
          currencySymbol={settings.currencySymbol}
          customCategories={categories}
          isDark={isDark}
        />

        <CategoryManagerModal
          isOpen={isCategoryManagerOpen}
          onClose={() => setIsCategoryManagerOpen(false)}
          categories={categories}
          onAddCategory={addCategory}
          onUpdateCategory={updateCategory}
          onDeleteCategory={deleteCategory}
          isDark={isDark}
        />

        <RecurringExpensesModal
          isOpen={isRecurringOpen}
          onClose={() => setIsRecurringOpen(false)}
          recurringExpenses={recurringExpenses}
          onAddRecurring={addRecurringExpense}
          onUpdateRecurring={updateRecurringExpense}
          onDeleteRecurring={deleteRecurringExpense}
          onToggleActive={toggleRecurringActive}
          onProcessDue={processDueRecurring}
          currencySymbol={settings.currencySymbol}
          defaultCurrency={settings.currency}
          categories={categories}
          isDark={isDark}
        />

        <BudgetWalletsModal
          isOpen={isBudgetWalletsOpen}
          onClose={() => setIsBudgetWalletsOpen(false)}
          expenses={expenses}
          currencySymbol={settings.currencySymbol}
          monthlyBudget={settings.monthlyBudget}
          categoryBudgets={settings.categoryBudgets || {}}
          categoryBudgetConfigs={settings.categoryBudgetConfigs || {}}
          onUpdateCategoryBudgets={(newBudgets) => {
            updateSettings({ categoryBudgets: newBudgets });
          }}
          onUpdateCategoryBudgetConfig={updateCategoryBudgetConfig}
          categories={categories}
          isDark={isDark}
        />

        <InteractiveWalkthrough
          isOpen={isWalkthroughOpen}
          onClose={() => setIsWalkthroughOpen(false)}
          onOpenScanner={() => setIsScannerOpen(true)}
          onOpenAddExpense={() => handleOpenAdd('expense')}
          onOpenAddIncome={() => handleOpenAdd('income')}
          onOpenRecurring={() => setIsRecurringOpen(true)}
          onOpenBudgetWallets={handleNavigateToBudgets}
          isDark={isDark}
        />

        {/* Excel & CSV Spreadsheet Importer Modal */}
        <ExcelImportModal
          isOpen={isExcelImportOpen}
          onClose={() => setIsExcelImportOpen(false)}
          onImportExpenses={addMultipleExpenses}
          defaultCurrency={settings.currency}
          isDark={isDark}
        />
      </div>
    </AndroidFrame>
  );
}
